feat: add branch name check

diff --git a/.github/workflows/github-ci.yml b/.github/workflows/github-ci.yml
--- a/.github/workflows/github-ci.yml
+++ b/.github/workflows/github-ci.yml
@@ -14,6 +14,15 @@ jobs:
         node-version: [20.x]
 
     steps:
+      - name: Check branch name
+        run: |
+          BRANCH_NAME=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
+          echo "Branch name: $BRANCH_NAME"
+          if [[ ! "$BRANCH_NAME" =~ ^(feature)/[a-zA-Z0-9._-]+$ ]]; then
+          echo "Invalid branch name: $BRANCH_NAME"
+          exit 1
+          fi
+          echo "Branch name is valid."
       - uses: actions/checkout@v4
       - name: Use Node.js
         uses: actions/setup-node@v4
